services:
  - type: web
    plan: free
    name: music
    env: python
    buildCommand: /Dockerfile
    startCommand: python3 -m Zaid
    repo: https://github.com/Dhrubamoy82/Telethon-Music      
    branch: render
    envVars:
      - key: API_ID 
        sync: false    
    autoDeploy: false
