services:
  - type: web
    plan: free
    name: music
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: gunicorn app:app & python3 -m Zaid
    repo: https://github.com/Dhrubamoy82/Telethon-Music      
    branch: master
    envVars:
      - key: ASSISTANT_ID 
        sync: false
      - key: BOT_TOKEN 
        sync: false
      - key: STRING_SESSION 
        sync: false    
    autoDeploy: false
