services:
  - type: web
    plan: free
    name: PYRO-RENAME-BOT
    env: python
    buildCommand: .
    startCommand: python3 -m Zaid
    repo: https://github.com/Dhrubamoy82/Telethon-Music      
    branch: main
    envVars:
      - key: API_ID 
        sync: false    
    autoDeploy: false
